#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=SlurmOutputs/slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
module load SWIG/4.0.2-GCCcore-11.3.0

# Activate your environment
source activate pg
# Check whether the GPU is available
srun python ThesisPlayground/pettingzoo/waterworld.py